version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "SenhaForte@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'"]
      interval: 5s
      timeout: 5s
      retries: 15



  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: gestor
      RABBITMQ_DEFAULT_PASS: gestor123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 10



  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Jwt__Key: "jZg86CTJOpYDij1pxn1XaVnZqyR+5/gxlmACGOqkq9bbsIRDGmJOy6Jjpc8PJpRQV99Tiin+rhODGM5N3Qrfsg=="
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=DbGestorDeClientes;User Id=sa;Password=SenhaForte@123;TrustServerCertificate=True"
  worker:
    build:
      context: .
      dockerfile: GestorDeClientes.Worker/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started
      sqlserver:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: gestor
      RabbitMQ__Password: gestor123


volumes:
  sqlserver_data:
